# 1) Install and load the Lahman library. This database includes data related to baseball teams. It includes summary statistics about how the players performed on offense and defense for several years. It also includes personal information about the players.
# The Batting data frame contains the offensive statistics for all players for many years. You can see, for example, the top 10 hitters by running this code:
    library(Lahman)

    top <- Batting |>
      filter(yearID == 2016) |>
      arrange(desc(HR)) |>
      slice(1:10)

    top |> as_tibble()
# But who are these players? We see an ID, but not the names. The player names are in this table

    People |> as_tibble()
# We can see column names nameFirst and nameLast. Use the left_join function to create a table of the top home run hitters. The table should have playerID, first name, last name, and number of home runs (HR). Rewrite the object top with this new table.

In [113]:
import pandas as pd

In [114]:
top = pd.read_csv("Batting.csv")
top

,playerID,yearID,stint,teamID,lgID,G,G_batting,AB,R,H,...,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,G_old
0,aardsda01,2004,1,SFN,NL,11,NaN,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1,aardsda01,2006,1,CHN,NL,45,NaN,2,0,0,...,0.0,0.0,0,0.0,0.0,0.0,1.0,0.0,0.0,NaN
2,aardsda01,2007,1,CHA,AL,25,NaN,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,aardsda01,2008,1,BOS,AL,47,NaN,1,0,0,...,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN
4,aardsda01,2009,1,SEA,AL,73,NaN,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113794,zwilldu01,1915,1,CHF,FL,150,NaN,548,65,157,...,24.0,NaN,67,65.0,NaN,2.0,18.0,NaN,NaN,NaN
113795,zwilldu01,1916,1,CHN,NL,35,NaN,53,4,6,...,0.0,NaN,4,6.0,NaN,0.0,2.0,NaN,NaN,NaN
113796,zychto01,2015,1,SEA,AL,13,NaN,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
113797,zychto01,2016,1,SEA,AL,12,NaN,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
113798,zychto01,2017,1,SEA,AL,45,NaN,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

In [115]:
top.head(10)

,playerID,yearID,stint,teamID,lgID,G,G_batting,AB,R,H,...,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,G_old
0,aardsda01,2004,1,SFN,NL,11,NaN,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1,aardsda01,2006,1,CHN,NL,45,NaN,2,0,0,...,0.0,0.0,0,0.0,0.0,0.0,1.0,0.0,0.0,NaN
2,aardsda01,2007,1,CHA,AL,25,NaN,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,aardsda01,2008,1,BOS,AL,47,NaN,1,0,0,...,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN
4,aardsda01,2009,1,SEA,AL,73,NaN,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
5,aardsda01,2010,1,SEA,AL,53,NaN,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
6,aardsda01,2012,1,NYA,AL,1,NaN,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
7,aardsda01,2013,1,NYN,NL,43,NaN,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
8,aardsda01,2015,1,ATL,NL,33,NaN,1,0,0,...,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN
9,aaronha01,1954,1,ML1,NL,122,NaN,468,58,131,...,2.0,2.0,28,39.0,NaN,3.0,6.0,4.0,13.0,NaN

In [116]:
top = top[top["yearID"] == 2016].sort_values(by=["HR"], ascending=False)
top

,playerID,yearID,stint,teamID,lgID,G,G_batting,AB,R,H,...,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,G_old
103772,trumbma01,2016,1,BAL,AL,159,NaN,613,94,157,...,2.0,0.0,51,170.0,1.0,3.0,0.0,0.0,14.0,NaN
22463,cruzne02,2016,1,SEA,AL,155,NaN,589,96,169,...,2.0,0.0,62,159.0,5.0,9.0,0.0,7.0,15.0,NaN
29385,encared01,2016,1,TOR,AL,160,NaN,601,99,158,...,2.0,0.0,87,138.0,3.0,5.0,0.0,8.0,22.0,NaN
24045,daviskh01,2016,1,OAK,AL,150,NaN,555,85,137,...,1.0,2.0,42,166.0,0.0,8.0,0.0,5.0,19.0,NaN
27201,doziebr01,2016,1,MIN,AL,155,NaN,615,104,165,...,18.0,2.0,61,138.0,6.0,8.0,2.0,5.0,12.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47970,hoytja01,2016,1,HOU,AL,22,NaN,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
47965,hoyinja01,2016,1,TEX,AL,39,NaN,46,8,10,...,1.0,0.0,3,8.0,0.0,0.0,0.0,0.0,0.0,NaN
47874,howeljp01,2016,1,LAN,NL,64,NaN,2,0,0,...,0.0,0.0,0,2.0,0.0,0.0,0.0,0.0,0.0,NaN
47611,housetj01,2016,1,CLE,AL,4,NaN,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
113797,zychto01,2016,1,SEA,AL,12,NaN,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

In [117]:
top = top[["playerID", "HR"]][:10]
top

         playerID  HR
103772  trumbma01  47
22463    cruzne02  43
29385   encared01  42
24045   daviskh01  42
27201   doziebr01  42
16151   cartech02  41
2819    arenano01  41
33647   frazito01  40
15320    canoro01  39
12752   bryankr01  39

In [118]:
people = pd.read_csv("People.csv", encoding="ISO-8859-1")
people

,ID,playerID,birthYear,birthMonth,birthDay,birthCity,birthCountry,birthState,deathYear,deathMonth,...,nameLast,nameGiven,weight,height,bats,throws,debut,bbrefID,finalGame,retroID
0,1,aardsda01,1981.0,12.0,27.0,Denver,USA,CO,NaN,NaN,...,Aardsma,David Allan,215.0,75.0,R,R,2004-04-06,aardsda01,2015-08-23,aardd001
1,2,aaronha01,1934.0,2.0,5.0,Mobile,USA,AL,2021.0,1.0,...,Aaron,Henry Louis,180.0,72.0,R,R,1954-04-13,aaronha01,1976-10-03,aaroh101
2,3,aaronto01,1939.0,8.0,5.0,Mobile,USA,AL,1984.0,8.0,...,Aaron,Tommie Lee,190.0,75.0,R,R,1962-04-10,aaronto01,1971-09-26,aarot101
3,4,aasedo01,1954.0,9.0,8.0,Orange,USA,CA,NaN,NaN,...,Aase,Donald William,190.0,75.0,R,R,1977-07-26,aasedo01,1990-10-03,aased001
4,5,abadan01,1972.0,8.0,25.0,Palm Beach,USA,FL,NaN,NaN,...,Abad,Fausto Andres,184.0,73.0,L,L,2001-09-10,abadan01,2006-04-13,abada001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21005,21006,paysojo99,1903.0,2.0,5.0,New York,USA,NY,1975.0,10.0,...,Payson,Joan Whitney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21006,21007,galbrjo99,1897.0,8.0,10.0,Derby,USA,OH,1988.0,7.0,...,Galbreath,John Wilmer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21007,21008,mcshejo99,1944.0,9.0,11.0,Bronx,USA,NY,1996.0,4.0,...,McSherry,John Patrick,351.0,75.0,NaN,NaN,NaN,NaN,NaN,mcshj901
21008,21009,weyerle99,1936.0,9.0,3.0,Imlay City,USA,MI,1988.0,7.0,...,Weyer,Lee Howard,258.0,78.0,NaN,NaN,NaN,NaN,NaN,weyel901
21009,21010,palerst99,1949.0,10.0,9.0,Worcester,USA,MA,2017.0,5.0,...,Palermo,Stephen Michael,175.0,74.0,NaN,NaN,NaN,NaN,NaN,pales901

In [119]:
top = pd.merge(top, people, on="playerID", how="left")
top = top[["playerID", "nameFirst", "nameLast", "HR"]]
top

    playerID nameFirst     nameLast  HR
0  trumbma01      Mark       Trumbo  47
1   cruzne02    Nelson         Cruz  43
2  encared01     Edwin  Encarnacion  42
3  daviskh01     Khris        Davis  42
4  doziebr01     Brian       Dozier  42
5  cartech02     Chris       Carter  41
6  arenano01     Nolan      Arenado  41
7  frazito01      Todd      Frazier  40
8   canoro01  Robinson         Cano  39
9  bryankr01      Kris       Bryant  39

# 2) Now use the Salaries data frame to add each player’s salary to the table you created in exercise 1. Note that salaries are different every year so make sure to filter for the year 2016, then use right_join. This time show first name, last name, team, HR, and salary.

In [120]:
salaries = pd.read_csv("Salaries.csv")
salaries

       yearID teamID lgID   playerID    salary
0        1985    ATL   NL  barkele01    870000
1        1985    ATL   NL  bedrost01    550000
2        1985    ATL   NL  benedbr01    545000
3        1985    ATL   NL   campri01    633333
4        1985    ATL   NL  ceronri01    625000
...       ...    ...  ...        ...       ...
26423    2016    WAS   NL  strasst01  10400000
26424    2016    WAS   NL  taylomi02    524000
26425    2016    WAS   NL  treinbl01    524900
26426    2016    WAS   NL  werthja01  21733615
26427    2016    WAS   NL  zimmery01  14000000

[26428 rows x 5 columns]

In [121]:
salaries = salaries[salaries["yearID"] == 2016]
salaries

       yearID teamID lgID   playerID    salary
25575    2016    ARI   NL  ahmedni01    521600
25576    2016    ARI   NL  barreja01    507500
25577    2016    ARI   NL  brachsi01    509300
25578    2016    ARI   NL  britoso01    508500
25579    2016    ARI   NL  castiwe01   3700000
...       ...    ...  ...        ...       ...
26423    2016    WAS   NL  strasst01  10400000
26424    2016    WAS   NL  taylomi02    524000
26425    2016    WAS   NL  treinbl01    524900
26426    2016    WAS   NL  werthja01  21733615
26427    2016    WAS   NL  zimmery01  14000000

[853 rows x 5 columns]

In [122]:
salaries = pd.merge(salaries, top, on="playerID", how="right")
salaries

   yearID teamID lgID   playerID    salary nameFirst     nameLast  HR
0    2016    BAL   AL  trumbma01   9150000      Mark       Trumbo  47
1    2016    SEA   AL   cruzne02  14250000    Nelson         Cruz  43
2    2016    TOR   AL  encared01  10000000     Edwin  Encarnacion  42
3    2016    OAK   AL  daviskh01    524500     Khris        Davis  42
4    2016    MIN   AL  doziebr01   3000000     Brian       Dozier  42
5    2016    MIL   NL  cartech02   2500000     Chris       Carter  41
6    2016    COL   NL  arenano01   5000000     Nolan      Arenado  41
7    2016    CHA   AL  frazito01   8250000      Todd      Frazier  40
8    2016    SEA   AL   canoro01  24000000  Robinson         Cano  39
9    2016    CHN   NL  bryankr01    652000      Kris       Bryant  39

In [123]:
salaries = salaries[["nameFirst", "nameLast", "teamID", "HR", "salary"]]
salaries

  nameFirst     nameLast teamID  HR    salary
0      Mark       Trumbo    BAL  47   9150000
1    Nelson         Cruz    SEA  43  14250000
2     Edwin  Encarnacion    TOR  42  10000000
3     Khris        Davis    OAK  42    524500
4     Brian       Dozier    MIN  42   3000000
5     Chris       Carter    MIL  41   2500000
6     Nolan      Arenado    COL  41   5000000
7      Todd      Frazier    CHA  40   8250000
8  Robinson         Cano    SEA  39  24000000
9      Kris       Bryant    CHN  39    652000

# 3) In a previous exercise, we created a tidy version of the co2 dataset:<br>
    co2_wide <- data.frame(matrix(co2, ncol = 12, byrow = TRUE)) |>
    setNames(1:12) |>
    mutate(year = 1959:1997) |>
    pivot_longer(-year, names_to = "month", values_to = "co2") |>
    mutate(month = as.numeric(month))
# We want to see if the monthly trend is changing so we are going to remove the year effects and then plot the results. We will first compute the year averages. Use the group_by and summarize to compute the average co2 for each year. Save in an object called yearly_avg.

In [124]:
import numpy as np
co2 = pd.read_csv('co2.csv')

data = co2['value'].tolist()
data = np.asarray(data)
co2_wide = pd.DataFrame( data.reshape(39,12), index = range(1959,1998), columns = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'])
co2_wide

,1,2,3,4,5,6,7,8,9,10,11,12
1959,315.42,316.31,316.50,317.56,318.13,318.00,316.39,314.65,313.68,313.18,314.66,315.43
1960,316.27,316.81,317.42,318.87,319.87,319.43,318.01,315.74,314.00,313.68,314.84,316.03
1961,316.73,317.54,318.38,319.31,320.42,319.61,318.42,316.63,314.83,315.16,315.94,316.85
1962,317.78,318.40,319.53,320.42,320.85,320.45,319.45,317.25,316.11,315.27,316.53,317.53
1963,318.58,318.92,319.70,321.22,322.08,321.31,319.58,317.61,316.05,315.83,316.91,318.20
1964,319.41,320.07,320.74,321.40,322.06,321.73,320.27,318.54,316.54,316.71,317.53,318.55
1965,319.27,320.28,320.73,321.97,322.00,321.71,321.05,318.71,317.66,317.14,318.70,319.25
1966,320.46,321.43,322.23,323.54,323.91,323.59,322.24,320.20,318.48,317.94,319.63,320.87
1967,322.17,322.34,322.88,324.25,324.83,323.93,322.38,320.76,319.10,319.24,320.56,321.80
1968,322.40,322.99,323.73,324.86,325.40,325.20,323.98,321.95,320.18,320.09,321.16,322.74
1969,323.83,324.26,325.47,326.50,327.21,326.54,325.72,323.50,322.22,321.62,322.69,323.95
1970,324.89,325.82,326.77,327.97,327.91,327.50,326.18,324.53,322.93,322.90,323.85,324.96
1971,326.01,326.51,327.01,327.62,328.76,328.40,327.20,325.27,323.20,323.40,324.63,325.85
1972,326.60,327.47,327.58,329.56,329.90,328.92,327.88,326.16,324.68,325.04,326.34,327.39
1973,328.37,329.40,330.14,331.33,332.31,331.90,330.70,329.15,327.35,327.02,327.99,328.48
1974,329.18,330.55,331.32,332.48,332.92,332.08,331.01,329.23,327.27,327.21,328.29,329.41
1975,330.23,331.25,331.87,333.14,333.80,333.43,331.73,329.90,328.40,328.17,329.32,330.59
1976,331.58,332.39,333.33,334.41,334.71,334.17,332.89,330.77,329.14,328.78,330.14,331.52
1977,332.75,333.24,334.53,335.90,336.57,336.10,334.76,332.59,331.42,330.98,332.24,333.68
1978,334.80,335.22,336.47,337.59,337.84,337.72,336.37,334.51,332.60,332.38,333.75,334.78
1979,336.05,336.59,337.79,338.71,339.30,339.12,337.56,335.92,333.75,333.70,335.12,336.56
1980,337.84,338.19,339.91,340.60,341.29,341.00,339.39,337.43,335.72,335.84,336.93,338.04
1981,339.06,340.30,341.21,342.33,342.74,342.08,340.32,338.26,336.52,336.68,338.19,339.44
1982,340.57,341.44,342.53,343.39,343.96,343.18,341.88,339.65,337.81,337.69,339.09,340.32
1983,341.20,342.35,342.93,344.77,345.58,345.14,343.81,342.21,339.69,339.82,340.98,342.82
1984,343.52,344.33,345.11,346.88,347.25,346.62,345.22,343.11,340.90,341.18,342.80,344.04
1985,344.79,345.82,347.25,348.17,348.74,348.07,346.38,344.51,342.92,342.62,344.06,345.38
1986,346.11,346.78,347.68,349.37,350.03,349.37,347.76,345.73,344.68,343.99,345.48,346.72
1987,347.84,348.29,349.23,350.80,351.66,351.07,349.33,347.92,346.27,346.18,347.64,348.78
1988,350.25,351.54,352.05,353.41,354.04,353.62,352.22,350.27,348.55,348.72,349.91,351.18
1989,352.60,352.92,353.53,355.26,355.52,354.97,353.75,351.52,349.64,349.83,351.14,352.37
1990,353.50,354.55,355.23,356.04,357.00,356.07,354.67,352.76,350.82,351.04,352.69,354.07
1991,354.59,355.63,357.03,358.48,359.22,358.12,356.06,353.92,352.05,352.11,353.64,354.89
1992,355.88,356.63,357.72,359.07,359.58,359.17,356.94,354.92,352.94,353.23,354.09,355.33
1993,356.63,357.10,358.32,359.41,360.23,359.55,357.53,355.48,353.67,353.95,355.30,356.78
1994,358.34,358.89,359.95,361.25,361.67,360.94,359.55,357.49,355.84,356.00,357.59,359.05
1995,359.98,361.03,361.66,363.48,363.82,363.30,361.94,359.50,358.11,357.80,359.61,360.74
1996,362.09,363.29,364.06,364.76,365.45,365.01,363.70,361.54,359.51,359.65,360.80,362.38
1997,363.23,364.06,364.61,366.40,366.84,365.68,364.52,362.57,360.24,360.83,362.49,364.34

In [125]:
temp = pd.DataFrame((round(co2_wide.mean(axis=1), 2)), columns = ['Avg'])
temp

         Avg
1959  315.83
1960  316.75
1961  317.48
1962  318.30
1963  318.83
1964  319.46
1965  319.87
1966  321.21
1967  322.02
1968  322.89
1969  324.46
1970  325.52
1971  326.16
1972  327.29
1973  329.51
1974  330.08
1975  330.99
1976  331.99
1977  333.73
1978  335.34
1979  336.68
1980  338.52
1981  339.76
1982  340.96
1983  342.61
1984  344.25
1985  345.73
1986  346.98
1987  348.75
1988  351.31
1989  352.75
1990  354.04
1991  355.48
1992  356.29
1993  357.00
1994  358.88
1995  360.91
1996  362.69
1997  363.82

# 4) Now use the left_join function to add the yearly average to the co2_wide dataset. Then compute the residuals: observed co2 measure - yearly average.

In [128]:
co2_wide = co2_wide.join(temp, how = 'left')
co2_wide

,1,2,3,4,5,6,7,8,9,10,11,12,Avg
1959,315.42,316.31,316.50,317.56,318.13,318.00,316.39,314.65,313.68,313.18,314.66,315.43,315.83
1960,316.27,316.81,317.42,318.87,319.87,319.43,318.01,315.74,314.00,313.68,314.84,316.03,316.75
1961,316.73,317.54,318.38,319.31,320.42,319.61,318.42,316.63,314.83,315.16,315.94,316.85,317.48
1962,317.78,318.40,319.53,320.42,320.85,320.45,319.45,317.25,316.11,315.27,316.53,317.53,318.30
1963,318.58,318.92,319.70,321.22,322.08,321.31,319.58,317.61,316.05,315.83,316.91,318.20,318.83
1964,319.41,320.07,320.74,321.40,322.06,321.73,320.27,318.54,316.54,316.71,317.53,318.55,319.46
1965,319.27,320.28,320.73,321.97,322.00,321.71,321.05,318.71,317.66,317.14,318.70,319.25,319.87
1966,320.46,321.43,322.23,323.54,323.91,323.59,322.24,320.20,318.48,317.94,319.63,320.87,321.21
1967,322.17,322.34,322.88,324.25,324.83,323.93,322.38,320.76,319.10,319.24,320.56,321.80,322.02
1968,322.40,322.99,323.73,324.86,325.40,325.20,323.98,321.95,320.18,320.09,321.16,322.74,322.89
1969,323.83,324.26,325.47,326.50,327.21,326.54,325.72,323.50,322.22,321.62,322.69,323.95,324.46
1970,324.89,325.82,326.77,327.97,327.91,327.50,326.18,324.53,322.93,322.90,323.85,324.96,325.52
1971,326.01,326.51,327.01,327.62,328.76,328.40,327.20,325.27,323.20,323.40,324.63,325.85,326.16
1972,326.60,327.47,327.58,329.56,329.90,328.92,327.88,326.16,324.68,325.04,326.34,327.39,327.29
1973,328.37,329.40,330.14,331.33,332.31,331.90,330.70,329.15,327.35,327.02,327.99,328.48,329.51
1974,329.18,330.55,331.32,332.48,332.92,332.08,331.01,329.23,327.27,327.21,328.29,329.41,330.08
1975,330.23,331.25,331.87,333.14,333.80,333.43,331.73,329.90,328.40,328.17,329.32,330.59,330.99
1976,331.58,332.39,333.33,334.41,334.71,334.17,332.89,330.77,329.14,328.78,330.14,331.52,331.99
1977,332.75,333.24,334.53,335.90,336.57,336.10,334.76,332.59,331.42,330.98,332.24,333.68,333.73
1978,334.80,335.22,336.47,337.59,337.84,337.72,336.37,334.51,332.60,332.38,333.75,334.78,335.34
1979,336.05,336.59,337.79,338.71,339.30,339.12,337.56,335.92,333.75,333.70,335.12,336.56,336.68
1980,337.84,338.19,339.91,340.60,341.29,341.00,339.39,337.43,335.72,335.84,336.93,338.04,338.52
1981,339.06,340.30,341.21,342.33,342.74,342.08,340.32,338.26,336.52,336.68,338.19,339.44,339.76
1982,340.57,341.44,342.53,343.39,343.96,343.18,341.88,339.65,337.81,337.69,339.09,340.32,340.96
1983,341.20,342.35,342.93,344.77,345.58,345.14,343.81,342.21,339.69,339.82,340.98,342.82,342.61
1984,343.52,344.33,345.11,346.88,347.25,346.62,345.22,343.11,340.90,341.18,342.80,344.04,344.25
1985,344.79,345.82,347.25,348.17,348.74,348.07,346.38,344.51,342.92,342.62,344.06,345.38,345.73
1986,346.11,346.78,347.68,349.37,350.03,349.37,347.76,345.73,344.68,343.99,345.48,346.72,346.98
1987,347.84,348.29,349.23,350.80,351.66,351.07,349.33,347.92,346.27,346.18,347.64,348.78,348.75
1988,350.25,351.54,352.05,353.41,354.04,353.62,352.22,350.27,348.55,348.72,349.91,351.18,351.31
1989,352.60,352.92,353.53,355.26,355.52,354.97,353.75,351.52,349.64,349.83,351.14,352.37,352.75
1990,353.50,354.55,355.23,356.04,357.00,356.07,354.67,352.76,350.82,351.04,352.69,354.07,354.04
1991,354.59,355.63,357.03,358.48,359.22,358.12,356.06,353.92,352.05,352.11,353.64,354.89,355.48
1992,355.88,356.63,357.72,359.07,359.58,359.17,356.94,354.92,352.94,353.23,354.09,355.33,356.29
1993,356.63,357.10,358.32,359.41,360.23,359.55,357.53,355.48,353.67,353.95,355.30,356.78,357.00
1994,358.34,358.89,359.95,361.25,361.67,360.94,359.55,357.49,355.84,356.00,357.59,359.05,358.88
1995,359.98,361.03,361.66,363.48,363.82,363.30,361.94,359.50,358.11,357.80,359.61,360.74,360.91
1996,362.09,363.29,364.06,364.76,365.45,365.01,363.70,361.54,359.51,359.65,360.80,362.38,362.69
1997,363.23,364.06,364.61,366.40,366.84,365.68,364.52,362.57,360.24,360.83,362.49,364.34,363.82

In [130]:
res_co2 = pd.DataFrame(index = range(1959,1998), columns = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'])
for i in range(1,13):
  res_co2[f'{i}'] = co2_wide[f'{i}'] - co2_wide['Avg']
res_co2

         1     2     3     4     5     6     7     8     9    10    11    12
1959 -0.41  0.48  0.67  1.73  2.30  2.17  0.56 -1.18 -2.15 -2.65 -1.17 -0.40
1960 -0.48  0.06  0.67  2.12  3.12  2.68  1.26 -1.01 -2.75 -3.07 -1.91 -0.72
1961 -0.75  0.06  0.90  1.83  2.94  2.13  0.94 -0.85 -2.65 -2.32 -1.54 -0.63
1962 -0.52  0.10  1.23  2.12  2.55  2.15  1.15 -1.05 -2.19 -3.03 -1.77 -0.77
1963 -0.25  0.09  0.87  2.39  3.25  2.48  0.75 -1.22 -2.78 -3.00 -1.92 -0.63
1964 -0.05  0.61  1.28  1.94  2.60  2.27  0.81 -0.92 -2.92 -2.75 -1.93 -0.91
1965 -0.60  0.41  0.86  2.10  2.13  1.84  1.18 -1.16 -2.21 -2.73 -1.17 -0.62
1966 -0.75  0.22  1.02  2.33  2.70  2.38  1.03 -1.01 -2.73 -3.27 -1.58 -0.34
1967  0.15  0.32  0.86  2.23  2.81  1.91  0.36 -1.26 -2.92 -2.78 -1.46 -0.22
1968 -0.49  0.10  0.84  1.97  2.51  2.31  1.09 -0.94 -2.71 -2.80 -1.73 -0.15
1969 -0.63 -0.20  1.01  2.04  2.75  2.08  1.26 -0.96 -2.24 -2.84 -1.77 -0.51
1970 -0.63  0.30  1.25  2.45  2.39  1.98  0.66 -0.99 -2.59 -2.62 -1.67 -0.56
1971 -0.15  0.35  0.85  1.46  2.60  2.24  1.04 -0.89 -2.96 -2.76 -1.53 -0.31
1972 -0.69  0.18  0.29  2.27  2.61  1.63  0.59 -1.13 -2.61 -2.25 -0.95  0.10
1973 -1.14 -0.11  0.63  1.82  2.80  2.39  1.19 -0.36 -2.16 -2.49 -1.52 -1.03
1974 -0.90  0.47  1.24  2.40  2.84  2.00  0.93 -0.85 -2.81 -2.87 -1.79 -0.67
1975 -0.76  0.26  0.88  2.15  2.81  2.44  0.74 -1.09 -2.59 -2.82 -1.67 -0.40
1976 -0.41  0.40  1.34  2.42  2.72  2.18  0.90 -1.22 -2.85 -3.21 -1.85 -0.47
1977 -0.98 -0.49  0.80  2.17  2.84  2.37  1.03 -1.14 -2.31 -2.75 -1.49 -0.05
1978 -0.54 -0.12  1.13  2.25  2.50  2.38  1.03 -0.83 -2.74 -2.96 -1.59 -0.56
1979 -0.63 -0.09  1.11  2.03  2.62  2.44  0.88 -0.76 -2.93 -2.98 -1.56 -0.12
1980 -0.68 -0.33  1.39  2.08  2.77  2.48  0.87 -1.09 -2.80 -2.68 -1.59 -0.48
1981 -0.70  0.54  1.45  2.57  2.98  2.32  0.56 -1.50 -3.24 -3.08 -1.57 -0.32
1982 -0.39  0.48  1.57  2.43  3.00  2.22  0.92 -1.31 -3.15 -3.27 -1.87 -0.64
1983 -1.41 -0.26  0.32  2.16  2.97  2.53  1.20 -0.40 -2.92 -2.79 -1.63  0.21
1984 -0.73  0.08  0.86  2.63  3.00  2.37  0.97 -1.14 -3.35 -3.07 -1.45 -0.21
1985 -0.94  0.09  1.52  2.44  3.01  2.34  0.65 -1.22 -2.81 -3.11 -1.67 -0.35
1986 -0.87 -0.20  0.70  2.39  3.05  2.39  0.78 -1.25 -2.30 -2.99 -1.50 -0.26
1987 -0.91 -0.46  0.48  2.05  2.91  2.32  0.58 -0.83 -2.48 -2.57 -1.11  0.03
1988 -1.06  0.23  0.74  2.10  2.73  2.31  0.91 -1.04 -2.76 -2.59 -1.40 -0.13
1989 -0.15  0.17  0.78  2.51  2.77  2.22  1.00 -1.23 -3.11 -2.92 -1.61 -0.38
1990 -0.54  0.51  1.19  2.00  2.96  2.03  0.63 -1.28 -3.22 -3.00 -1.35  0.03
1991 -0.89  0.15  1.55  3.00  3.74  2.64  0.58 -1.56 -3.43 -3.37 -1.84 -0.59
1992 -0.41  0.34  1.43  2.78  3.29  2.88  0.65 -1.37 -3.35 -3.06 -2.20 -0.96
1993 -0.37  0.10  1.32  2.41  3.23  2.55  0.53 -1.52 -3.33 -3.05 -1.70 -0.22
1994 -0.54  0.01  1.07  2.37  2.79  2.06  0.67 -1.39 -3.04 -2.88 -1.29  0.17
1995 -0.93  0.12  0.75  2.57  2.91  2.39  1.03 -1.41 -2.80 -3.11 -1.30 -0.17
1996 -0.60  0.60  1.37  2.07  2.76  2.32  1.01 -1.15 -3.18 -3.04 -1.89 -0.31
1997 -0.59  0.24  0.79  2.58  3.02  1.86  0.70 -1.25 -3.58 -2.99 -1.33  0.52

---

# 5)Make a plot of the seasonal trends by year but only after removing the year effect.

Exercício: 13. Advanced: extract the titles of the movies that won Best Picture from this website: https://m.imdb.com/chart/bestpicture/

**Minha abordagem:**<br>
A página apresenta somente 50 títulos por vez. E para exibição dos próximos itens é necessário clicar sobre um botão que realiza uma chamada assincrona obtendo mais resultados. Seria possível implementar um web scraping utilizando Selenium porém não conseguiria demonstrar aqui por notebook.<br>

Percebi que o site possibilitava reordenar os registros por ano gerando uma nova URL, contendo parâmetros para a ordenação, como demonstrado abaixo:<br><br>

URL após a ordenação por ano do mais antigo para o mais recente:
https://m.imdb.com/search/title/?groups=best_picture_winner&sort=year,asc

URL após a ordenação por ano do mais recente para o mais antigo:
https://m.imdb.com/search/title/?groups=best_picture_winner&sort=year,desc

In [ ]:
import requests
import re
from bs4 import BeautifulSoup

#Link original: "https://m.imdb.com/chart/bestpicture/"

links = [
    "https://m.imdb.com/search/title/?groups=best_picture_winner&sort=year,asc",
    "https://m.imdb.com/search/title/?groups=best_picture_winner&sort=year,desc"
]


"""
Função para carregamento do conteúdo de uma URL informada

:param site_url: Link (URL) da página a ser carregada
:return: retorna um objeto contendo os dados da resposta da requisição
"""
def load_site(site_url):
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36',
    }

    response = requests.get(link, headers=headers)

    print(f'URL requisitada: {link}')

    if response.status_code == 200 :
        print(f"Sucesso: código de retorno {response.status_code}")
        return response
    else :
        print(f'Falha na requisição - código do erro: {response.status_code}')


pages = []

for link in links:
    response = load_site(link)
    pages.append(BeautifulSoup(response.text, 'html.parser'))

pages

Abaixo obtenho os elementos HTML que contém a lista de títulos (de ambas URLS). Estes objetos são armazenados em uma lista chamada **titles**

In [ ]:
movies_titles = []
for page in pages:
    movies_titles.append(page.find_all("li", class_="ipc-metadata-list-summary-item"))

movies_titles

Agora para cada uma das listas de títulos de filmes extraio o conteúdo de texto contento do nome do título do filme. Estas duas listas serão a base para criação de DataFrames, onde farei o merge e a eliminação de possíveis elementos duplicados.

In [ ]:
"""
"""
def get_movie_titles(movie_list):
    titles = []
    for item in movie_list:
        titles.append({
            'title' : re.sub("\d+. ", "", item.find("h3", class_="ipc-title__text").getText()),
            'release'  : item.find_all("span", class_="dli-title-metadata-item")[0].getText(),
            'runtime'  : item.find_all("span", class_="dli-title-metadata-item")[1].getText()
        })
    return titles

#Dicionário contendo a lista de títulos final e tratada
titles = ()

Extraindo os títulos da lista ordenada de forma decrescente (título mais recente para o mais antigo) [Qtde. de títulos: 50]

In [ ]:

titles_list_1 = get_movie_titles(movies_titles[1])
titles_list_1

Extraindo os títulos da lista ordenada de forma crescente (título mais antigo para o mais recente) [Qtde. de títulos: 50]<br>
Observações:
* A lista irá sobrepor alguns título da lista anterior, para remover vou utilizar um set (conjunto)
* É necessário reverter a ordem da lista para dicar igual à lista anterior (do mais recente para o mais antigo)

In [ ]:
titles_list_2 = get_movie_titles(movies_titles[0])
titles_list_2.reverse()
titles_list_2

Junção das listas em um set (conjunto)

In [ ]:
df1 = pd.DataFrame(titles_list_1)
df1

In [ ]:
df2 = pd.DataFrame(titles_list_2)
df2

Combinando os DataFrames

In [ ]:
movies = pd.concat([df1, df2], ignore_index=True, sort=False)
movies

Removendo os títulos duplicados

In [ ]:
movies = movies.drop_duplicates()
movies